language: perl
# ony old precise has archived -thr builds, but even that fails to install
perl:
  #- "5.6.2-thr"
  - "5.8"
  - "5.10"
  #- "5.10.1-thr"
  #  dist: precise
  #  sudo: required
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
  - "5.26"
  - "5.28"
  - "5.28-thr"
  - "dev-thr-mb-shrplib-dbg"
#  - "cperl-5.26.1"
sudo: false
before_install:
  - perl -V
  - ulimit -s
install:
  - perl Makefile.PL
  - make
script:
  - cpanm -n Test::Kwalitee Test::CheckManifest Test::CPAN::Meta Pod::Spell::CommonMistakes Test::Spelling Test::Pod Devel::Refcount
  - make test TEST_VERBOSE=1
