skip_tags: true

cache:
  - C:\strawberry

install:
  - if not exist "C:\strawberry" cinst strawberryperl -y
  - set PATH=C:\strawberry\perl\bin;C:\strawberry\perl\site\bin;C:\strawberry\c\bin;%PATH%
  - cd C:\projects\%APPVEYOR_PROJECT_NAME%

build_script:
  #- ppm install dmake
  #- perl Makefile.PL MAKE=dmake
  - perl Makefile.PL MAKE=gmake
  - gmake

test_script:
  - cpanm -n Test::Kwalitee Test::CheckManifest Test::CPAN::Meta Pod::Spell::CommonMistakes Test::Spelling Test::Pod Devel::Refcount
  - set STORABLE_NOISY=1
  - gmake test TEST_VERBOSE=1
