---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 8.0404, CPAN::Meta::Converter version 2.150010'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Storable
no_index:
  directory:
    - t
    - inc
requires:
  Test::More: '0.41'
  XSLoader: '0'
resources:
  bugtracker: https://github.com/rurban/Storable/issues/
  repository: https://github.com/rurban/Storable/
version: 3.05_14
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
