---
abstract: 'persistence for Perl data structures'
author:
  - 'Reini Urban'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.24, CPAN::Meta::Converter version 2.150010, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Storable
no_index:
  directory:
    - t
    - inc
provides:
  Storable:
    file: Storable_pm.PL
    version: 3.12_03
requires:
  XSLoader: 0
resources:
  bugtracker: http://rt.perl.org/perlbug/
version: 3.12_03
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
