---
abstract: 'persistence for Perl data structures'
author:
  - 'Perl 5 Porters'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.24, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name:         Storable
no_index:
  directory:
    - t
    - inc
provides:
  Storable:
    file: __Storable__.pm
    version: '3.11'
requires:
  XSLoader: '0'
resources:
  bugtracker: http://rt.perl.org/perlbug/
version: '3.11'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
